s = set()

n=input("Enter a Number")
s.add(int(n))
n=input("Enter a Number")
s.add(int(n))
n=input("Enter a Number")
s.add(int(n))
n=input("Enter a Number")
s.add(int(n))
n=input("Enter a Number")
s.add(int(n))
n=input("Enter a Number")
s.add(int(n))
n=input("Enter a Number")
s.add(int(n))
print(s)